site_name: Cirrus Platform
site_description: Enterprise Internal Developer Platform (IDP)
site_url: https://joaocciriaco.github.io/cirrus-platform/

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: indigo
    accent: blue
  features:
    - navigation.indexes
    - navigation.sections
    - search.suggest
    - content.code.copy

nav:
  - Visão Geral: README.md
  - Arquitetura:
      - Modelo C4: docs/architecture/C4_MODEL.md